# Generated by Django 4.2.28 on 2026-03-12 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('frame', models.IntegerField(verbose_name='帧号')),
                ('track_id', models.IntegerField(verbose_name='轨迹ID')),
                ('bb_left', models.FloatField(verbose_name='边界框左上角X')),
                ('bb_top', models.FloatField(verbose_name='边界框左上角Y')),
                ('bb_width', models.FloatField(verbose_name='边界框宽度')),
                ('bb_height', models.FloatField(verbose_name='边界框高度')),
                ('conf', models.FloatField(verbose_name='置信度')),
                ('class_id', models.IntegerField(default=0, verbose_name='类别')),
                ('visibility', models.FloatField(blank=True, null=True, verbose_name='可见性')),
            ],
            options={
                'verbose_name': '细胞',
                'verbose_name_plural': '细胞',
                'db_table': 'cells',
            },
        ),
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('model_path', models.CharField(max_length=255, verbose_name='模型路径')),
            ],
            options={
                'verbose_name': '模型',
                'verbose_name_plural': '模型',
                'db_table': 'models',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('task_id', models.CharField(max_length=36, unique=True, verbose_name='任务ID')),
                ('task_name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度（0-100）')),
                ('conf', models.FloatField(default=0.3, verbose_name='置信度阈值')),
                ('imgsz', models.IntegerField(default=1024, verbose_name='图像尺寸')),
                ('fps', models.IntegerField(default=10, verbose_name='帧率')),
                ('annotated_video_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='标注视频名称')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='邮箱')),
                ('password_hash', models.CharField(max_length=255, verbose_name='密码哈希')),
                ('dark_mode', models.BooleanField(default=True, verbose_name='深色模式')),
                ('model_base_path', models.CharField(default='models', max_length=500, verbose_name='模型基础路径')),
                ('output_base_path', models.CharField(default='output', max_length=500, verbose_name='输出基础路径')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('video_name', models.CharField(max_length=255, verbose_name='视频名称')),
                ('video_path', models.CharField(max_length=255, verbose_name='视频路径')),
                ('total_frames', models.IntegerField(blank=True, null=True, verbose_name='总帧数')),
                ('video_duration', models.FloatField(blank=True, null=True, verbose_name='视频时长（秒）')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小（字节）')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.user', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'db_table': 'videos',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted'], name='users_is_dele_21b557_idx'),
        ),
        migrations.AddField(
            model_name='task',
            name='model',
            field=models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.modelfile', verbose_name='模型'),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.user', verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='task',
            name='video',
            field=models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.video', verbose_name='视频'),
        ),
        migrations.AddField(
            model_name='modelfile',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.user', verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='cell',
            name='task',
            field=models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.task', verbose_name='所属任务'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['user'], name='videos_user_id_b36f3e_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['user', 'is_deleted'], name='videos_user_id_5e3d85_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_deleted'], name='videos_is_dele_0c597a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('user', 'video_name')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_id'], name='tasks_task_id_869377_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user'], name='tasks_user_id_e70422_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'status'], name='tasks_user_id_a53e17_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'is_deleted'], name='tasks_user_id_69d547_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['video'], name='tasks_video_i_a07226_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['model'], name='tasks_model_i_b4881f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='tasks_created_db4e37_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'status', 'is_deleted'], name='tasks_user_id_3e0044_idx'),
        ),
        migrations.AddIndex(
            model_name='modelfile',
            index=models.Index(fields=['user'], name='models_user_id_a8fd6b_idx'),
        ),
        migrations.AddIndex(
            model_name='modelfile',
            index=models.Index(fields=['user', 'is_deleted'], name='models_user_id_09a8fd_idx'),
        ),
        migrations.AddIndex(
            model_name='modelfile',
            index=models.Index(fields=['is_deleted'], name='models_is_dele_cbedfc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modelfile',
            unique_together={('user', 'model_name')},
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['task'], name='cells_task_id_195705_idx'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['task', 'frame', 'track_id'], name='cells_task_id_33d82c_idx'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['task', 'track_id'], name='cells_task_id_f2faba_idx'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['task', 'frame'], name='cells_task_id_2542dc_idx'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['task', 'is_deleted'], name='cells_task_id_c1f17b_idx'),
        ),
    ]
