# Generated by Django 4.2.28 on 2026-03-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="current_frame",
            field=models.IntegerField(default=0, verbose_name="当前帧"),
        ),
        migrations.AddField(
            model_name="task",
            name="stage",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="阶段"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="total_frames",
            field=models.IntegerField(default=0, verbose_name="总帧数"),
        ),
        migrations.AlterField(
            model_name="user",
            name="model_base_path",
            field=models.CharField(max_length=500, verbose_name="模型基础路径"),
        ),
        migrations.AlterField(
            model_name="user",
            name="output_base_path",
            field=models.CharField(max_length=500, verbose_name="输出基础路径"),
        ),
    ]
