# Generated by Django 4.2.28 on 2026-03-16 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_current_frame_task_stage_task_total_frames_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='current_frame',
        ),
        migrations.RemoveField(
            model_name='task',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='task',
            name='stage',
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度（0-100）')),
                ('stage', models.CharField(blank=True, max_length=50, null=True, verbose_name='当前阶段')),
                ('current_frame', models.IntegerField(default=0, verbose_name='当前处理帧数')),
                ('total_frames', models.IntegerField(default=0, verbose_name='总帧数')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('estimated_remaining_time', models.IntegerField(blank=True, null=True, verbose_name='预计剩余时间（秒）')),
                ('task', models.OneToOneField(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, to='api.task', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '任务状态',
                'verbose_name_plural': '任务状态',
                'db_table': 'task_status',
                'indexes': [models.Index(fields=['task'], name='task_status_task_id_ce26b0_idx'), models.Index(fields=['task', 'status'], name='task_status_task_id_3554b3_idx'), models.Index(fields=['status'], name='task_status_status_4792e8_idx')],
            },
        ),
    ]
