# Generated by Django 4.2.28 on 2026-03-16 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_task_current_frame_remove_task_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='task',
            field=models.OneToOneField(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, to='api.task', to_field='task_id', verbose_name='关联任务'),
        ),
    ]
