# Generated by Django 4.2.28 on 2026-03-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_taskstatus_task"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="task",
            new_name="idx_task_id",
            old_name="tasks_task_id_869377_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="idx_user_id",
            old_name="tasks_user_id_e70422_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="idx_user_status",
            old_name="tasks_user_id_a53e17_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="idx_user_deleted",
            old_name="tasks_user_id_69d547_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="idx_video_id",
            old_name="tasks_video_i_a07226_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="idx_model_id",
            old_name="tasks_model_i_b4881f_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="idx_created_at",
            old_name="tasks_created_db4e37_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="idx_user_status_deleted",
            old_name="tasks_user_id_3e0044_idx",
        ),
        migrations.RenameIndex(
            model_name="taskstatus",
            new_name="idx_task_status_id",
            old_name="task_status_task_id_ce26b0_idx",
        ),
        migrations.RenameIndex(
            model_name="taskstatus",
            new_name="idx_task_status",
            old_name="task_status_task_id_3554b3_idx",
        ),
        migrations.RenameIndex(
            model_name="taskstatus",
            new_name="idx_status",
            old_name="task_status_status_4792e8_idx",
        ),
        migrations.AddField(
            model_name="cell",
            name="area",
            field=models.FloatField(default=0.0, verbose_name="面积"),
        ),
        migrations.AddField(
            model_name="cell",
            name="metrics_json",
            field=models.JSONField(
                default={
                    "bbox": {"height": 0.0, "left": 0.0, "top": 0.0, "width": 0.0},
                    "cell_class": 0,
                    "center": {"cx": 0.0, "cy": 0.0},
                    "confidence": 1.0,
                    "motion": {
                        "distance": 0.0,
                        "mean_square_displacement": 0.0,
                        "migration_speed": 0.0,
                        "persistence_index": 0.0,
                        "turning_angle": 0.0,
                        "vx": 0.0,
                        "vy": 0.0,
                    },
                    "shape": {
                        "aspect_ratio": 0.0,
                        "circularity": 0.0,
                        "circularity_increment": 0.0,
                        "perimeter": 0.0,
                        "protrusion_activity_index": 0.0,
                        "shape_change_rate": 0.0,
                        "spreading_index": 0.0,
                    },
                    "visibility": 1.0,
                },
                verbose_name="聚合后的指标 JSON",
            ),
        ),
        migrations.AddField(
            model_name="cell",
            name="speed",
            field=models.FloatField(default=0.0, verbose_name="速度"),
        ),
        migrations.AddField(
            model_name="cell",
            name="tracking_persistence",
            field=models.FloatField(default=0.0, verbose_name="持续追踪度"),
        ),
    ]
