# Generated by Django 4.2.28 on 2026-03-19 09:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_tasks_task_id_869377_idx_idx_task_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cell",
            name="metrics_json",
            field=models.JSONField(
                default=api.models.Cell.get_default_metrics,
                verbose_name="聚合后的指标 JSON",
            ),
        ),
    ]
