# Generated by Django 4.2.28 on 2026-03-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cell_metrics_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='total_frames',
        ),
    ]
