# Generated by Django 4.2.28 on 2026-03-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_task_total_frames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstatus',
            name='estimated_remaining_time',
        ),
    ]
